<?php
return [
    // 是否启用
    'enabled' => env('SYSTEMLOG_ENABLED', true),

    // 默认只记录写操作（强烈推荐）
    'only_write_methods' => true,

    // 统一脱敏字段（全端通用）
    'mask_keys' => ['pay_password', 'password', 'password_confirmation', 'amount_password', 'google_2fa_code', 'captcha', 'token', 'api_token', 'authorization', 'secret', 'api_secret', 'app_secret', 'appsecret', 'private_key', 'privatekey', 'sign', 'signature', 'key', 'appkey'],
    // 直接从日志参数中移除的字段
    'drop_keys' => ['_token', 'telegram_bot_token', 'captcha', 'captchaType', 'google_2fa_code'],
    // 描述字段已移除（不再使用）
    // subject 类型中文映射（class_basename => 中文）
    'subject_labels' => [
        'AdminAdministrator' => '管理员',
        'AdminRole' => '角色',
        'AdminSetting' => '系统配置',
        'AdminUser' => '管理员',
        'AgentUser' => '商户代理',
        'BankCode' => '银行编码',
        'BlackContent' => '黑名单',
        'Channel' => '渠道',
        'ChannelAccount' => '渠道账号',
        'ChannelRate' => '渠道成本',
        'DepositOrder' => '代收订单',
        'FreezeOrder' => '冻结订单',
        'MerchantBalanceLog' => '商户流水',
        'MerchantChannel' => '商户渠道',
        'MerchantInfo' => '商户信息',
        'MerchantMenu' => '商户菜单',
        'MerchantPayment' => '商户费率',
        'MerchantUser' => '商户用户',
        'TransferOrder' => '代付订单',
        'User' => '金主(代理)',
        'UserBank' => '收款卡',
        'UserGroup' => '用户分组',
        'UserModel' => '金主(代理)',
        "MerchantRole" => "商户角色"
    ],
    'describe_max_fields' => 4,
    'describe_value_max_length' => 60,
    // 操作者下拉可选数量上限
    'causer_select_limit' => 2000,
    // 变更字段展示配置（中文）
    'change_labels_cn' => [
        'transfer_test_confirm_on' => '代付测试确认开关',
        'transfer_test_confirm_telegram_group_id' => '代付测试确认通知群ID',
        'transfer_test_confirm_min_amount' => '代付测试确认金额',
        'transfer_test_confirm_expire_minutes' => '代付测试确认过期时间',
        'merchant_balance_adjust_confirm_on' => '商户人工加项确认开关',
        'merchant_balance_adjust_confirm_telegram_group_id' => '商户人工加项确认通知群ID',
        'merchant_balance_adjust_confirm_min_amount' => '商户人工加项确认金额',
        'merchant_balance_adjust_confirm_expire_minutes' => '商户人工加项确认过期时间',
        'deposit_manual_success_confirm_on' => '人工补单确认开关',
        'deposit_manual_success_confirm_telegram_group_id' => '人工补单确认通知群',
        'deposit_manual_success_confirm_min_amount' => '人工补单确认金额',
        'deposit_manual_success_confirm_expire_minutes' => '人工补单确认过期时间',
        'user_login_exception_notice_switch' => '系统登录异常通知开关',
        'user_login_exception_notice_telegram_group_ids' => '系统登录异常通知群',
        // 按模型映射
        'MerchantInfo' => [
            'merchant_user_id' => '商户ID',
            'agent_user_id' => '代理ID',
            'coder' => '商户编码',
            'appkey' => 'AppKey',
            'appsecret' => 'AppSecret',
            'pay_white_ip' => '代收白名单IP',
            'withdraw_white_ip' => '代付白名单IP',
            'callback_white_ip' => '回调白名单IP',
            'amount_float_type' => '浮动类型',
            'float_amount' => '浮动金额',
            'currency_id' => '币种',
            'balance_amount' => '余额',
            'name' => '商户名称',
            'deposits_callback_url' => '代收回调地址',
            'transfer_callback_url' => '代付回调地址',
            'available_balance' => '可用余额',
            'freeze_amount' => '冻结资金',
            'settlement_amount' => '结算资金',
            'history_balance_amount' => '历史余额',
            'last_balance_amount_time' => '最后变动时间',
            'history_end_balance_amount_time' => '截止时间点',
            'deposit_notice' => '代收通知',
            'transfer_notice' => '代付通知',
            'is_need_decimal' => '需要小数',
            'deposit_channel_mode' => '代收渠道模式',
            'transfer_channel_mode' => '代付渠道模式',
            'is_usdt_ava_rate' => '计算USDT平均费率',
            'okx_payment_method' => '支付方式',
            'okx_side' => '模式',
            'okx_user_type' => '类型',
            'okx_index' => '档位',
            'default_usdt_ava_rate' => 'USDT默认费率',
            'usdt_float_rate' => 'USDT浮动费率',
            'usdt_ava_rate' => 'USDT平均费率',
            'available_usdt_balance' => 'USDT总额',
            'auto_transfer' => '自动代付',
            'cashier_domain' => '收营台域名',
            'check_order' => '订单反查',
            'sign_space' => '签名空格',
            'system_create_ip' => '系统生成IP',
        ],
        'MerchantUser' => [
            'username' => '用户名',
            'name' => '名称',
            'avatar' => '头像',
            'session_id' => '会话ID',
            'login_white_ip' => '登录提现IP白名单',
            'status' => '启用状态',
            'password' => '密码',
            'remember_token' => '记住Token',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'MerchantChannel' => [
            'merchant_user_id' => '商户ID',
            'channel_id' => '渠道ID',
            'payment_id' => '支付ID',
            'priority' => '优先级',
            'status' => '状态',
            'float_status' => '浮动状态',
            'pay_min_amount' => '代收单笔下限',
            'pay_max_amount' => '代收单笔上限',
            'collection_min_amount' => '代付单笔下限',
            'collection_max_amount' => '代付单笔上限',
            'fee' => '代付额外手续费',
            'deposit_fee' => '代收额外手续费',
            'settlement_mode' => '结算模式',
            'settlement_time' => '结算时间',
            'use_cashier' => '系统收营台',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ],
        'AgentUser' => [
            'username' => '代理用户名',
            'name' => '代理名称',
            'password' => '登录密码',
            'status' => '启用状态',
            'login_white_ip' => '登录IP白名单',
            'pid' => '上级代理',
            'level' => '代理层级',
            'google' => '谷歌验证器',
            'last_login_ip' => '最后登录IP',
            'last_login_time' => '最后登录时间',
            'balance_amount' => '余额',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'AdminAdministrator' => [
            'username' => '管理员用户名',
            'name' => '管理员姓名',
            'password' => '登录密码',
            'status' => '账号状态',
            'login_white_ip' => '登录IP白名单',
            'google' => '谷歌验证器',
            'google_two_fa_bind' => '谷歌验证码绑定',
            'last_login_ip' => '最后登录IP',
            'last_login_time' => '最后登录时间',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'AdminRole' => [
            'slug' => '角色标识',
            'name' => '角色名称',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'BankCode' => [
            'currency_id' => '所属国家',
            'code' => '银行代码',
            'name' => '银行名称',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'BlackContent' => [
            'type' => '类型',
            'content' => '内容',
            'mid' => '所属商户',
            'status' => '启用状态',
            'remark' => '备注',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'UserModel' => [
            'username' => '金主用户名',
            'name' => '金主名称',
            'password' => '登录密码',
            'status' => '账号状态',
            'acquisition_status' => '接单状态',
            'action_collection_status' => '自主开关收款卡',
            'self_add_bank' => '自主操作收款卡',
            'action_delete' => '自主操作删除',
            'action_limit_card' => '自主操作收款限制',
            'mobile' => '金主手机号',
            'collection_limit_min' => '代收单笔最低限额',
            'collection_limit_max' => '代收单笔最高限额',
            'pay_limit_min' => '代付单笔最低限额',
            'pay_limit_max' => '代付单笔最高限额',
            'limit_deposit_paid_number' => '代收待付款相同金额订单限制',
            'account_types' => '收款卡类型',
            'pay_group_merchant_user_ids' => '商户代付分组标示',
            'collection_group_merchant_ids' => '商户代收分组标示',
            'user_group_id' => '推送分组',
            'remark' => '备注',
            'google_two_fa_enable' => '谷歌验证码状态',
            'google_two_fa_secret' => '谷歌密钥',
            'google_two_fa_bind' => '谷歌验证码绑定',
            'level' => '层级',
            'pid' => '上级代理',
            'user_rate' => '金主费率',
            'agent1_rate' => '一级代理费率',
            'agent2_rate' => '二级代理费率',
            'agent3_rate' => '三级代理费率',
            'agent4_rate' => '四级代理费率',
            'agent5_rate' => '五级代理费率',
            'deposit_user_rate' => '金主代收费率',
            'deposit_agent1_rate' => '一级代理代收费率',
            'deposit_agent2_rate' => '二级代理代收费率',
            'deposit_agent3_rate' => '三级代理代收费率',
            'deposit_agent4_rate' => '四级代理代收费率',
            'deposit_agent5_rate' => '五级代理代收费率',
            'transfer_user_rate' => '金主代付费率',
            'transfer_agent1_rate' => '一级代理代付费率',
            'transfer_agent2_rate' => '二级代理代付费率',
            'transfer_agent3_rate' => '三级代理代付费率',
            'transfer_agent4_rate' => '四级代理代付费率',
            'transfer_agent5_rate' => '五级代理代付费率',
            'settlement_user_rate' => '金主结算费率',
            'settlement_agent1_rate' => '一级代理结算费率',
            'settlement_agent2_rate' => '二级代理结算费率',
            'settlement_agent3_rate' => '三级代理结算费率',
            'settlement_agent4_rate' => '四级代理结算费率',
            'settlement_agent5_rate' => '五级代理结算费率',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'User' => [
            'username' => '金主用户名',
            'name' => '金主名称',
            'password' => '登录密码',
            'status' => '账号状态',
            'acquisition_status' => '接单状态',
            'action_collection_status' => '自主开关收款卡',
            'self_add_bank' => '自主操作收款卡',
            'action_delete' => '自主操作删除',
            'action_limit_card' => '自主操作收款限制',
            'mobile' => '金主手机号',
            'collection_limit_min' => '代收单笔最低限额',
            'collection_limit_max' => '代收单笔最高限额',
            'pay_limit_min' => '代付单笔最低限额',
            'pay_limit_max' => '代付单笔最高限额',
            'limit_deposit_paid_number' => '代收待付款相同金额订单限制',
            'account_types' => '收款卡类型',
            'pay_group_merchant_user_ids' => '商户代付分组标示',
            'collection_group_merchant_ids' => '商户代收分组标示',
            'user_group_id' => '推送分组',
            'remark' => '备注',
            'google_two_fa_enable' => '谷歌验证码状态',
            'google_two_fa_secret' => '谷歌密钥',
            'google_two_fa_bind' => '谷歌验证码绑定',
            'level' => '层级',
            'pid' => '上级代理',
            'user_rate' => '金主费率',
            'agent1_rate' => '一级代理费率',
            'agent2_rate' => '二级代理费率',
            'agent3_rate' => '三级代理费率',
            'agent4_rate' => '四级代理费率',
            'agent5_rate' => '五级代理费率',
            'deposit_user_rate' => '金主代收费率',
            'deposit_agent1_rate' => '一级代理代收费率',
            'deposit_agent2_rate' => '二级代理代收费率',
            'deposit_agent3_rate' => '三级代理代收费率',
            'deposit_agent4_rate' => '四级代理代收费率',
            'deposit_agent5_rate' => '五级代理代收费率',
            'transfer_user_rate' => '金主代付费率',
            'transfer_agent1_rate' => '一级代理代付费率',
            'transfer_agent2_rate' => '二级代理代付费率',
            'transfer_agent3_rate' => '三级代理代付费率',
            'transfer_agent4_rate' => '四级代理代付费率',
            'transfer_agent5_rate' => '五级代理代付费率',
            'settlement_user_rate' => '金主结算费率',
            'settlement_agent1_rate' => '一级代理结算费率',
            'settlement_agent2_rate' => '二级代理结算费率',
            'settlement_agent3_rate' => '三级代理结算费率',
            'settlement_agent4_rate' => '四级代理结算费率',
            'settlement_agent5_rate' => '五级代理结算费率',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'UserBank' => [
            'user_id' => '金主ID',
            'payment_id' => '通道类型',
            'account_type' => '账号类型',
            'name' => '收款人姓名',
            'bank_id' => '开户行',
            'card_no' => '账号',
            'payment_qrcode' => '收款码',
            'collection_status' => '收款卡收款状态',
            'limint_min_amount' => '单笔限制下限',
            'limint_max_amount' => '单笔限制上限',
            'limint_day_amount' => '全天总额限制',
            'limit_day_order_number' => '全天总单数限制',
            'balance_amount' => '实际收款金额',
            'remark' => '备注',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'Channel' => [
            'name' => '渠道名称',
            'code' => '渠道代码',
            'telegram_user_id' => '群组ID',
            'payment_ids' => '支付方式',
            'status' => '渠道状态',
            'batch_transfer' => '批量代付',
            'auto_query_status' => '自动查询',
            'deposit_order_query' => '支持代收手动查询',
            'transfer_order_query' => '支持代付手动查询',
            'is_json_return' => '支持返卡',
            'use_cashier' => '使用系统收银台',
            'cashier_payment' => '支持收银台',
            'is_real_name' => '需要实名',
            'classname' => '支付类名',
            'transfer_payment' => '代付方式',
            'currency' => '支持币种',
            'coder' => '支付编码',
            'callback_white_ip' => '回调IP白名单',
            'appsecret' => 'AppSecret',
            'balance_amount' => '账户余额',
            'balance_update_time' => '余额更新时间',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'ChannelAccount' => [
            'channel_id' => '渠道ID',
            'name' => '账号名称',
            'status' => '状态',
            'pay_min_amount' => '充值单笔下限',
            'pay_max_amount' => '充值单笔上限',
            'pay_total_amount' => '充值日总额',
            'collection_min_amount' => '代付单笔下限',
            'collection_max_amount' => '代付单笔上限',
            'collection_total_amount' => '代付日总额',
            'params' => '账号参数',
            'secret_params' => '保密参数1',
            'public_params' => '保密参数2',
            'debug_logs' => '调试状态',
            'balance_amount' => '余额',
            'balance_update_time' => '余额更新时间',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'ChannelRate' => [
            'channel_id' => '渠道ID',
            'payment_id' => '通道类型',
            'type' => '费率类型',
            'rate' => '成本费率',
            'fixed_rate' => '固定费率',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'UserGroup' => [
            'name' => '分组名称',
            'priority' => '优先级',
            'status' => '状态',
            'specialized_merchant_user_ids' => '专接商户标识',
            'merchant_user_ids' => '排除商户标识',
            'extra_user_ids' => '补充金主',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
        ],
        'MerchantPayment' => [
            'merchant_user_id' => '商户ID',
            'agent_user_id' => '代理ID',
            'payment_id' => '通道类型',
            'status' => '启用状态',
            'pay_rate' => '支付费率',
            'agent1_rate' => '一级代理费率',
            'agent2_rate' => '二级代理费率',
            'agent3_rate' => '三级代理费率',
            'min_limit_amount' => '单笔最低限额',
            'max_limit_amount' => '单笔最高限额',
            'transfer_rates' => '银行代付费率',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ],
        // 默认映射（不分模型）
        'google_two_fa_bind' => '谷歌验证码绑定',
    ],
    'change_max_fields' => 15,
    'change_value_max_length' => 80,
    'ignore_paths' => [
        '_ignition/*',
        'horizon/*',
        'captcha/*',
        // 统一忽略登录/验证，避免落入操作日志
        '*/auth/login',
        '*/auth/verify',
        // 登录/验证码相关（不记日志）
        ltrim((string)config('admin.route.prefix', 'admin'), '/') . '/auth/login',
        ltrim((string)config('admin.route.prefix', 'admin'), '/') . '/captcha/*',
        ltrim((string)config('merchant-admin.route.prefix', 'merchant-admin'), '/') . '/auth/login',
        ltrim((string)config('merchant-admin.route.prefix', 'merchant-admin'), '/') . '/captcha/*',
        ltrim((string)config('agent-admin.route.prefix', 'agent-admin'), '/') . '/auth/login',
        ltrim((string)config('agent-admin.route.prefix', 'agent-admin'), '/') . '/captcha/*',
        'api/v2/captcha*',
        // dcat ajax/api (prefixes are dynamic)
        ltrim((string)config('admin.route.prefix', 'admin'), '/') . '/ajax*',
        ltrim((string)config('admin.route.prefix', 'admin'), '/') . '/dcat-api*',
        ltrim((string)config('agent-admin.route.prefix', 'agent-admin'), '/') . '/dcat-api*',
        ltrim((string)config('merchant-admin.route.prefix', 'merchant-admin'), '/') . '/dcat-api*',
    ],
    'ignore_route_names' => [
        // dcat api route names (prefix is dynamic)
        'dcat.*.dcat-api*',
    ],
    'apps' => [
        'user' => [
            'guard' => 'sanctum',
            'log_name' => 'user',
            'title' => '金主(代理)',
        ],
        'admin' => [
            'guard' => 'admin',
            'log_name' => 'admin',
            'title' => '管理员',
        ],
        'merchant' => [
            'guard' => 'merchant-admin',
            'log_name' => 'merchant',
            'title' => '商户',
        ],
        'agent' => [
            'guard' => 'agent-admin',
            'log_name' => 'agent',
            'title' => '商户代理',
        ],
    ],

    /**
     * 行为映射（建议按「路由名」来映射，最稳定）
     * key: route name
     */
    'actions' => [
        'admin' => [
        // 商户渠道
        'dcat.admin.merchant-channels.store' => '新增 商户渠道配置',
        'dcat.admin.merchant-channels.update' => '修改 商户渠道配置',
        'dcat.admin.merchant-channels.destroy' => '删除 商户渠道配置',
        'merchant.channel.batch_open' => '批量开启 商户渠道',
        'merchant.channel.batch_close' => '批量关闭 商户渠道',
        'merchant.channel.batch_open_float' => '批量开启 商户渠道浮动',
        'merchant.channel.batch_close_float' => '批量关闭 商户渠道浮动',
        'merchant.channel.batch_add' => '批量新增 商户渠道',
        'merchant.channel.batch_update_collection_limit' => '批量修改 商户渠道代付限额',
        'merchant.channel.batch_update_pay_limit' => '批量修改 商户渠道代收限额',

        // 商户用户
        'dcat.admin.merchant.users.store' => '新增 商户用户',
        'dcat.admin.merchant.users.update' => '修改 商户用户',
        'merchant.user.unlock' => '解锁 商户登录',
        'merchant.user.reset_telegram' => '重置 商户飞机绑定',
        'merchant.user.delete' => '删除 商户用户',
        'merchant.user.reset_google' => '重置 商户谷歌验证码',
        'merchant.user.reset_password' => '重置 商户密码',
        'merchant.user.white_ip' => '设置 商户白名单',

        // 商户信息
        'dcat.admin.merchant.info.store' => '新增 商户信息',
        'dcat.admin.merchant.info.update' => '修改 商户信息',

        // 商户代理
        'dcat.admin.agent.users.store' => '新增 商户代理',
        'dcat.admin.agent.users.update' => '修改 商户代理',
        'agent.user.delete' => '删除 商户代理',
        'agent.user.reset_google' => '重置 商户代理谷歌验证码',
        'agent.user.unlock' => '解锁 商户代理登录',
        'agent.balance.add' => '增加 商户代理余额',
        'agent.balance.reduce' => '减少 商户代理余额',

        // 管理员
        'dcat.admin.auth.users.store' => '新增 管理员',
        'dcat.admin.auth.users.update' => '修改 管理员',
        'dcat.admin.auth.users.destroy' => '删除 管理员',
        'admin.user.reset_google' => '重置 管理员谷歌验证码',

        // 角色
        'dcat.admin.auth.roles.store' => '新增 角色',
        'dcat.admin.auth.roles.update' => '修改 角色',
        'dcat.admin.auth.roles.destroy' => '删除 角色',

        // 金主
        'dcat.admin.tusers.store' => '新增 金主',
        'dcat.admin.tusers.update' => '修改 金主',
        'user.delete' => '删除 金主',
        'user.unlock' => '解锁 金主(代理)登录',
        'user.force_logout' => '强制 金主(代理)退出登录',
        'user.reset_google' => '重置 金主谷歌验证码',
        'user.update_agent' => '调整 金主代理',
        'user.deposit_amount.add' => '增加 金主保证金',
        'user.deposit_amount.reduce' => '减少 金主保证金',
        'user.commission.add' => '增加 金主佣金',
        'user.commission.reduce' => '减少 金主佣金',
        'user.transfer.add' => '增加 金主代付账户余额',
        'user.transfer.reduce' => '减少 金主代付账户余额',
        'user.deposit.add' => '增加 金主代收账户余额',
        'user.deposit.reduce' => '减少 金主代收账户余额',
        'user.balance.add' => '增加 金主余额',
        'user.balance.reduce' => '减少 金主余额',
        'user.reset_password' => '重置 金主密码',

        //金主代理
        'dcat.admin.agents.store' => '新增 金主代理',
        'dcat.admin.agents.update' => '修改 金主代理',
        'user.agent.delete' => '删除 金主代理',

        // 收款卡
        'dcat.admin.bank-users.store' => '新增 收款卡',
        'dcat.admin.bank-users.update' => '修改 收款卡',
        'userbank.delete' => '删除 收款卡',
        'userbank.copy' => '复制 收款卡',
        'userbank.balance.add' => '增加 收款卡余额',
        'userbank.balance.reduce' => '减少 收款卡余额',
        'userbank.batch.open' => '批量开启 收款卡',
        'userbank.batch.close' => '批量关闭 收款卡',
        'userbank.batch.copy' => '批量复制 收款卡',
        'userbank.batch.update_limit' => '批量修改 收款卡限额',
        'userbank.recover' => '还原 收款卡',

        // 银行代码
        'dcat.admin.bank-codes.store' => '新增 银行代码',
        'dcat.admin.bank-codes.update' => '修改 银行代码',
        'dcat.admin.bank-codes.destroy' => '删除 银行代码',

        // 渠道
        'dcat.admin.channels.store' => '新增 渠道',
        'dcat.admin.channels.update' => '修改 渠道',
        'dcat.admin.channels.destroy' => '删除 渠道',

        // 渠道账号
        'dcat.admin.channel-accounts.store' => '新增 渠道账号',
        'dcat.admin.channel-accounts.update' => '修改 渠道账号',
        'dcat.admin.channel-accounts.destroy' => '删除 渠道账号',

        // 商户费率
        'dcat.admin.merchant-payments.store' => '新增 商户费率',
        'dcat.admin.merchant-payments.update' => '修改 商户费率',
        'dcat.admin.merchant-payments.destroy' => '删除 商户费率',
        'merchant.payment.batch_update_rate' => '批量修改 商户费率',
        'merchant.payment.batch_update_limit' => '批量修改 商户费率限额',

        // 用户分组
        'dcat.admin.group-users.store' => '新增 用户分组',
        'dcat.admin.group-users.update' => '修改 用户分组',
        'dcat.admin.group-users.destroy' => '删除 用户分组',

        // 渠道成本
        'dcat.admin.rates-channels.store' => '新增 渠道成本',
        'dcat.admin.rates-channels.update' => '修改 渠道成本',
        'dcat.admin.rates-channels.destroy' => '删除 渠道成本',
        'settlement.order.claim' => '结算订单 认领',
        'settlement.order.success' => '结算订单 成功',
        'settlement.order.fail' => '结算订单 失败',
        'settlement.order.channel' => '结算订单 选择渠道',

        // 代收/代付/冻结订单
        'deposit.order.success' => '代收订单成功',
        'deposit.order.fail' => '代收订单 失败',
        'deposit.order.freeze' => '冻结 代收订单',
        'transfer.order.success' => '代付订单 成功',
        'transfer.order.fail' => '代付订单 失败',
        'transfer.order.channel' => '代付订单 选择渠道',
        'transfer.order.corre' => '代付订单 冲正',
        'transfer.order.batch_submit' => '批量提交 代付订单',
        'freeze.order.unfreeze' => '解冻 冻结订单',

        // 配置/工具
        'admin.config.base.update' => '修改 基础配置',
        'admin.config.deposit.update' => '修改 代收配置',
        'admin.config.transfer.update' => '修改 代付配置',
        'admin.config.notice.update' => '修改 通知配置',
        'admin.config.telegram.update' => '修改 飞机配置',
        'admin.config.merchant.update' => '修改 商户配置',
        'admin.config.risk.update' => '修改 风控配置',
        'admin.config.okx.update' => '修改 欧易配置',
        'admin.config.security.update' => '修改 安全配置',
        'admin.selfchannel.config.update' => '修改 金主通道配置',
        'admin.home.test.store' => '测试代收下单',
        'admin.home.test.transfer.store' => '测试代付下单',
        'admin.home.telegram.group_send' => '飞机群发',

        // 余额
        'merchant.balance.add' => '增加 商户余额',
        'merchant.balance.reduce' => '减少 商户余额',

        // 黑名单
        'dcat.admin.black-contents.store' => '新增 黑名单',
        'dcat.admin.black-contents.update' => '修改 黑名单',
        'dcat.admin.black-contents.destroy' => '删除 黑名单',
        ],
        'merchant' => [
            'merchant.role.store' => '新增 商户角色',
            'merchant.role.update' => '修改 商户角色',
            'merchant.role.destroy' => '删除 商户角色',
            'merchant.user.update_password' => '修改 登录密码',
            'merchant.user.update_amount_password' => '修改 资金密码',
            'merchant.user.reset_google' => '重置 谷歌验证码',
            'merchant.secret.view' => '查看 密钥信息',
            'merchant.secret.reset' => '重置 密钥信息',
            'merchant.settlement.apply' => '提交 结算订单',
        ],
        'agent' => [
            'agent.login.success' => '登录成功',
            'agent.login.fail' => '登录失败',
            'agent.user.update_password' => '修改 代理登录密码',
        ],
        'user' => [
            // 金主端用户操作
            'api.v2.users.users.update-password' => '修改 登录密码',
            'api.v2.users.users.set-deposit-notice' => '设置 代收通知',
            'api.v2.users.users.set-transfer-notice' => '设置 代付通知',
            'api.v2.users.users.set-auto-refresh' => '设置 自动刷新',
            'api.v2.users.user-banks.store' => '新增 收款卡',
            'api.v2.users.user-banks.update' => '修改 收款卡',
            'api.v2.users.user-banks.destroy' => '删除 收款卡',
            'api.v2.users.user-banks.clear-bank' => '清空 收款卡',
            'api.v2.users.agent-users.bank-store' => '新增 代理收款卡',
            'api.v2.users.agent-users.bank-update' => '修改 代理收款卡',
            'api.v2.users.agent-users.bank-destroy' => '删除 代理收款卡',
            'api.v2.users.transfer-orders.submit-order' => '提交 代付订单凭证',
            'api.v2.users.transfer-orders.cancel-order' => '取消 代付订单',
            'api.v2.users.transfer-orders.receive-order' => '接单 代付订单',
            'api.v2.users.deposit-orders.confirm-pay' => '确认 代收订单',
        ],
    ],
];
